version: "3.9"
services:
  client:
    build: ./flipkart
    ports:
      - "3000:3000"
    depends_on:
      - web
      - mongo
  admin:
    build: ./admin
    ports:
      - "3001:3000"
    depends_on:
      - web
      - mongo
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - TOKENSECRATE=lksdajlkjslkajklklsfakklsajkljakljflkjjlkajkljfjflklkksakfjdsafljkajskslsa
      - DATABASE_URL=mongodb://mongo:27017/flipkart
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-express-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
  mongo-express-data:
    driver: local
