version: "3.3"
services:
  flipkart-clone-frontend:
    build: ./flipkart
    ports:
      - "3000:3000"
    depends_on:
      - flipkart-clone-backend
      - mongo
  flipkart-clone-admin:
    build: ./admin
    ports:
      - "3001:3000"
    depends_on:
      - flipkart-clone-backend
      - mongo
  flipkart-clone-backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - TOKENSECRATE=lksdajlkjslkajklklsfakklsajkljakljflkjjlkajkljfjflklkksakfjdsafljkajskslsa
      - DATABASE_URL=mongodb://mongo:27017/flipkart
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
  mongo-data:
    driver: local
